name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (but don't do anything with it)
      run: docker build . --file Dockerfile --tag zerocube-dhook:$(date +%s)
