# Pushes a tag if one doesn't exist for the current version.
on:
  push:
    branches:
      - main

jobs:
  determine_version:
    name: Get Version Number
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - id: get_version
      name: Get version from command line
      run: |
        APP_VERSION="$(go run . --version)"
        echo ::set-output name=version::${APP_VERSION}
        echo "APP_VERSION: ${APP_VERSION}"
    - name: Upsert repository tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
